# Generated by Django 5.1.3 on 2024-11-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_name',
            field=models.CharField(default=True, max_length=150),
        ),
    ]
