# Generated by Django 5.1.3 on 2024-11-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cartitem_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_of_product',
            field=models.CharField(default=True, max_length=150),
        ),
    ]
